# Generated by Django 3.2 on 2021-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_category_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='articles/'),
        ),
    ]
